import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>ERC20 Swapper</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to DAI Swapper
          </h1>

          <p className={styles.description}>
            Get started by selecting a{' '}
            <code className={styles.code}>Swap Scenario</code>
          </p>

          <div className={styles.grid}>
            <a href="/eth-dai" className={styles.card}>
              <h2>ETH &rarr; DAI</h2>
            </a>

            <a href="/dai-eth" className={styles.card}>
              <h2>DAI &rarr; ETH</h2>
            </a>
          </div>
        </main>
      </div>
    </Layout>
  )
}
